ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb.devopspractice.online
REDIS_HOST: redis.devopspractice.online
CATALOGUE_HOST: catalogue.devopspractice.online
CART_HOST: cart.devopspractice.online
MYSQL_HOST: mysql.devopspractice.online
USER_HOST: user.devopspractice.online
RABBITMQ_HOST: rabbitmq.devopspractice.online
SHIPPING_HOST: shipping.devopspractice.online
PAYMENT_HOST: payment.devopspractice.online