- name: configure the mongodb
  hosts: mongodb
  become: yes
  tasks:
    - name: copying the mongo
      copy:    
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: Install mongod server
      ansible.builtin.package:
        name: mongodb-org
        state: present
         

    # - name: replace the text in the repo file
    #   replace:
    #      regexp: '127.0.0.1'
    #      replace: '0.0.0.0'

      