# - name: configure the catalogue server
#   hosts: catalogue
#   become: yes
#   tasks:
#    - name: enable nodejs 20
#      command: dnf module enable nodejs:20 -y
  
#    - name: install nodejs 20
#      package: 
#       - name: nodejs 
#         state: present

#    - name: create a system user
#      user:
#        name: roboshop
#        system: true
#        home: /app
#        shell: /sbin/nologin
#        comment: "roboshop system user "



- name: configure the catalogue server
  hosts: catalogue
  become: yes
  tasks:
    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs 20
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: create a system user
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: remvoe the /app
      ansible.builtin.file:
         path: /app
         state: absent
  
    - name: remvoe the catalogue zip file
      ansible.builtin.file:
         path: /tmp/catalogue.zip
         state: absent

# creating a /app directory
    - name: create the /app
      ansible.builtin.file:
         path: /app
         state: directory
  
    - name: download the catalogue
      ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
         dest: /tmp/catalogue.zip
    - name: unzip unarchive
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue services
      template:
        src: catalogue.service.je
        dest: /etc/systemd/system/catalogue.service
    - name: copying the mongo
      copy:    
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb-mongosh 
      ansible.builtin.package:
        name: mongodb-mongosh
        state: present

    - name: Load products
      shell: mongosh --host "{{ MONGODB_HOST  }}"  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output
      tags:
        - mongodb
    - name: print out put
      debug: "{{ catalogeu_output}}"
      tags:
        - mongodb