# - name: configure the catalogue server
#   hosts: catalogue
#   become: yes
#   tasks:
#    - name: enable nodejs 20
#      command: dnf module enable nodejs:20 -y
  
#    - name: install nodejs 20
#      package: 
#       - name: nodejs 
#         state: present

#    - name: create a system user
#      user:
#        name: roboshop
#        system: true
#        home: /app
#        shell: /sbin/nologin
#        comment: "roboshop system user "



- name: configure the catalogue server
  hosts: catalogue
  become: yes
  tasks:
    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs 20
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: create a system user
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"
